// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "frc/commands/Subsystem.h"
#include "frc/WPILib.h"
#include "rev/CANSparkMax.h"
#include "ctre/Phoenix.h"
#include <cmath>

#define ENCODER_CNTS_PER_REV 4096

#define INNER_MAX_RPM 18730
#define INNNER_GEAR_RATIO 49.0
#define INNER_SPROCKET_PITCH 1.432
#define INNER_MAGIC_VELOCITY 2457			// 27"/sec = 2.7"/100 msec = .6 rev/100 msec = 2457 cnts/100 msec
#define INNER_MAGIC_ACCEL	(INNER_MAGIC_VELOCITY * 3)		// accel in terms of cnts/100msec / second

#define OUTER_MAX_RPM 5676
#define OUTER_GEAR_RATIO 14.2
#define OUTER_SPROCKET_PITCH 1.432
#define OUTER_MAGIC_VELOCITY 20			// inches/sec
#define OUTER_MAGIC_ACCEL (OUTER_MAGIC_VELOCITY * 3) 	// inches/sec^2

#define REAR_MAX_RPM 5840
#define REAR_GEAR_RATIO 81.0
#define REAR_SMALL_SPROCKET_PITCH 1.432
#define REAR_LARGE_SPROKET_PITCH 1.751
#define REAR_DRUM_DIAMETER 1.22

#define IN_POSITION_DEADBAND 0.25
/**
 *
 *
 * @author ExampleAuthor
 */
class Elevator: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::DigitalInput> limitSwitchInnerTop;
	std::shared_ptr<frc::DigitalInput> limitSwitchInnerBottom;
	std::shared_ptr<WPI_TalonSRX> talonInnerFront;
	std::shared_ptr<WPI_TalonSRX> talonRear;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	const int sparkElevatorID = 5;
	const double kTs = 0.02;		// 20 msec tick for periodic
	const double kPVinner;
	const double kVMaxInner;		// inner elevator Vmax
	const double kP_Inner;
	const double kD_Inner;
	const double kI_Inner;
	const double kF_Inner;
	const double kP_Outer;
	const double kD_Outer;
	const double kI_Outer;
	const double kF_Outer;
	const bool bMagic;

	const double kMaxOutput = 1, kMinOutput = -1;

	const double kPVouter;
	const double kVMaxOuter;		// outer elevator Vmax
	const double kPVrear;
	const double kVMaxRear;			// rear elevator Vmax

	const double kMaxInnerPos = 20.0;
	const double kMinInnerPos = 0.0;
	const double kMaxOuterPos = 20.0;
	const double kMinOuterPos = 0.0;
	std::shared_ptr<rev::CANSparkMax> sparkMaxOuter;
	std::shared_ptr<rev::CANEncoder> sparkMaxOuterEncoder;
	std::shared_ptr<rev::CANPIDController> pidOuter;

	double mInnerPosCmd = 0.0;
	double mOuterPosCmd = 0.0;
	double mRearPosCmd = 0.0;
	void ControlElevatorPositions();
	void ControlInnerPosition(bool bMagic = false);
	void ControlOuterPosition(bool bMagic = false);
	void ControlRearPosition();
	void StopAllElevators();
	void StopInner();
	void StopOuter();
	void StopRear();
	double GetInnerPos() { return talonInnerFront->GetSelectedSensorPosition(0);}
	double GetRearPos() { return talonRear->GetSelectedSensorPosition(0);}
	double GetOuterPos() { return sparkMaxOuter->GetEncoder().GetPosition();}
	double inchesToRotationsOuter(double inches);
	double rotationsToInchesOuter(double rotations);
	double inchesToCountsInner(double inches);
	double countsToInchesInner(double counts);
	double inchesToCountsRear(double inches);
	double countsToInchesRear(double counts);

public:
	Elevator();
	void InitDefaultCommand() override;
	void Periodic() override;
	bool LimitInnerTop() { return limitSwitchInnerTop->Get();}
	bool LimitInnerBottom() { return limitSwitchInnerBottom->Get();}
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	void SetInnerPosition(double pos) { mInnerPosCmd = pos;}
	void SetOuterPosition(double pos) { mOuterPosCmd = -pos;}
	void SetRearPosition(double pos) { mRearPosCmd = pos;}
	bool InnerAtPosition();
	bool OuterAtPosition();
	bool RearAtPosition();
	double GetInnerPosInches();
	double GetInnerCmd() { return mInnerPosCmd;}
	double GetRearPosInches();
	double GetOuterPosInches();
	double GetOuterCmd() { return -mOuterPosCmd;}
};

#endif
