// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/IntakeDown.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeDown::IntakeDown(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

/**
 * @brief Called just before this Command runs the first time
 */
void IntakeDown::Initialize() {

}

/**
 * @brief Called repeatedly when this Command is scheduled to run
 * 
 * Set both the left and right servos to the proper position to lower the intake
 */
void IntakeDown::Execute() {
    Robot::intake->IntakeDown();
}

/**
 * @brief Make this return true when this Command no longer needs to run execute()
 * 
 * @return true (to make this command an instant one)
 */
bool IntakeDown::IsFinished() {
    return true;
}

/**
 * @brief Called once after isFinished returns true
 */
void IntakeDown::End() {

}

/**
 * @brief Called when another command which requires one or more of the same subsystems is scheduled to run
 */
void IntakeDown::Interrupted() {

}
