// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/overrideDriveForward.h"
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

overrideDriveForward::overrideDriveForward(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

/**
 * @brief Called just before this Command runs the first time
 */
void overrideDriveForward::Initialize() {}

/**
 * @brief Called repeatedly when this Command is scheduled to run
 * 
 * Read both the y axis on the operator joystick.
 * Then move the inner and outer elevators up/down a given amount (in inches)
 */
void overrideDriveForward::Execute() {
    double xSpeedOverride = 0.5;
    Robot::driveTrain->VelocityArcade(xSpeedOverride, 0, false);
}

/**
 * @brief Make this return true when this Command no longer needs to run execute()
 * 
 * @return false (by default)
 */
bool overrideDriveForward::IsFinished() {
    return false;
}

/**
 * @brief Called once after isFinished returns true
 */
void overrideDriveForward::End() {}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void overrideDriveForward::Interrupted() {}
