// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/TeleopElevatorOverrideDown.h"
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TeleopElevatorOverrideDown::TeleopElevatorOverrideDown(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

/**
 * @brief Called just before this Command runs the first time
 */
void TeleopElevatorOverrideDown::Initialize() {

}

/**
 * @brief Called repeatedly when this Command is scheduled to run
 * 
 * Read both the y axis on the operator joystick.
 * Then move the inner and outer elevators up/down a given amount (in inches)
 */
void TeleopElevatorOverrideDown::Execute() {
    double cmdInnerOverride2 = -0.5;
    
    bool stopInner = false;
    bool stopOuter = false;

    if (fabs(cmdInnerOverride2) < 0.2)
    {
        cmdInnerOverride2 = 0.0;
    } 

    Robot::elevator->SlewInner(cmdInnerOverride2);
}

/**
 * @brief Make this return true when this Command no longer needs to run execute()
 * 
 * @return false (by default)
 */
bool TeleopElevatorOverrideDown::IsFinished() {
    return false;
}

/**
 * @brief Called once after isFinished returns true
 */
void TeleopElevatorOverrideDown::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TeleopElevatorOverrideDown::Interrupted() {

}
