// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/TeleopIntake.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TeleopIntake::TeleopIntake(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

/**
 * @brief Called just before this Command runs the first time
 */
void TeleopIntake::Initialize() {

}

/**
 * @brief Called repeatedly when this Command is scheduled to run
 * 
 * This method turns on the intake and keeps it running until a button is depressed
 */
void TeleopIntake::Execute() {
    Robot::intake->IntakeOn();
}

/**
 * @brief Make this return true when this Command no longer needs to run execute()
 * 
 * @return false (by default)
 */
bool TeleopIntake::IsFinished() {
    return false;
}

/**
 * @brief Called once after isFinished returns true
 * 
 * When the button is no longer pressed, turn off the intake
 */
void TeleopIntake::End() {
    Robot::intake->IntakeOff();
}

/**
 * @brief Called when another command which requires one or more of the same subsystems is scheduled to run
 */
void TeleopIntake::Interrupted() {
    End();
}
