// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Elevator.h"
#include "Commands/TeleopElevator.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Elevator::Elevator() : frc::Subsystem("Elevator") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    limitSwitchInnerTop.reset(new frc::DigitalInput(0));
    limitSwitchInnerBottom.reset(new frc::DigitalInput(1));
    talonInnerFront.reset(new WPI_TalonSRX(7));
    talonRear.reset(new WPI_TalonSRX(8));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    sparkMaxOuter.reset(new rev::CANSparkMax(sparkElevatorID, rev::CANSparkMax::MotorType::kBrushless));

    // setup elevator motors
    talonInnerFront->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, 0);
    talonInnerFront->SetSensorPhase(true);
    talonInnerFront->SetSelectedSensorPosition(0, 0);

    talonRear->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, 0);
    talonRear->SetSensorPhase(true);
    talonRear->SetSelectedSensorPosition(0, 0);

    pidOuter.reset(new rev::CANPIDController(sparkMaxOuter->GetPIDController()));
}

void Elevator::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new TeleopElevator());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Elevator::Periodic() {
    // Put code here to be run every loop
    SetElevatorPositions();
}

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Elevator::SetElevatorPositions() {
    SetInnerPosition();
    SetOuterPosition();
    SetRearPosition();
}

void Elevator::SetInnerPosition() {
    double cmd = mInnerPosCmd;
    talonInnerFront->Set(ControlMode::Position, cmd);
}

void Elevator::SetOuterPosition() {
    double cmd = mOuterPosCmd;
    pidOuter->SetReference(cmd, rev::ControlType::kPosition);
}

void Elevator::SetRearPosition() {
    double cmd = mRearPosCmd;
    talonRear->Set(ControlMode::Position, cmd);
}

void Elevator::StopAllElevators() {
    StopInner();
    StopOuter();
    StopRear();
}

void Elevator::StopInner() {
    mInnerPosCmd = GetInnerPos();
}

void Elevator::StopRear() {
    mRearPosCmd = GetRearPos();
}

void Elevator::StopOuter() {
    mOuterPosCmd = GetOuterPos();
}
